2015/06/16 15:56:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/registrar".' in /home/solis/Área de Trabalho/PROJETO TCC/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /home/solis/Área de Trabalho/PROJETO TCC/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/registrar')
#1 /home/solis/Área de Trabalho/PROJETO TCC/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/tcc/smdbyii/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=user/registrar
HTTP_REFERER=http://localhost/tcc/smdbyii/index.php?r=site/login
---
2015/06/16 22:31:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=gii
---
2015/06/16 22:35:55 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/tcc/smdbyii/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/tcc/smdbyii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/tcc/smdbyii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /var/www/html/tcc/smdbyii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /var/www/html/tcc/smdbyii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/tcc/smdbyii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/tcc/smdbyii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/tcc/smdbyii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/tcc/smdbyii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/tcc/smdbyii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/tcc/smdbyii/index.php?r=gii/default/index
---
2015/06/16 22:39:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/tcc/smdbyii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/tcc/smdbyii/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/tcc/smdbyii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/tcc/smdbyii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /var/www/html/tcc/smdbyii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /var/www/html/tcc/smdbyii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/tcc/smdbyii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/tcc/smdbyii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/tcc/smdbyii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/tcc/smdbyii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/tcc/smdbyii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#15 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/tcc/smdbyii/index.php?r=gii/module/index
---
2015/06/16 23:03:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('user')
#1 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=user
---
2015/06/16 23:09:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/registrar".' in /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/registrar')
#1 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=user/registrar
HTTP_REFERER=http://localhost/tcc/smdbyii/index.php?r=site/login
---
2015/06/16 23:11:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/tcc/smdbyii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 /var/www/html/tcc/smdbyii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/html/tcc/smdbyii/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tcc/smdbyii/index.php?r=user/admin
---
